/**
 * The utillib library. More information is available at http://www.jinchess.com/. Copyright (C)
 * 2007 Alexander Maryanovsky. All rights reserved.
 *
 * The utillib library is free software; you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * The utillib library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with utillib
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */
package free.util.swing.tabbedpane;

import java.util.EventListener;

/**
 * The listener interface for events generated by <code>TabbedPaneModel</code>.
 */
public interface TabbedPaneListener extends EventListener {

  /**
   * Invoked when a tab is added.
   */
  void tabAdded(TabbedPaneEvent evt);

  /**
   * Invoked when a tab is removed.
   */
  void tabRemoved(TabbedPaneEvent evt);

  /**
   * Invoked when a tab is selected.
   */
  void tabSelected(TabbedPaneEvent evt);

  /**
   * Invoked when a tab is deselected.
   */
  void tabDeselected(TabbedPaneEvent evt);
}
