#!/bin/bash

# The name of the created .dmg file
imagename=$1

# The size of the sparse image. It needs to be bigger than the real size
imagesize=$2

volumename=$3

# The directory to create the image from
targetname=$4


# Create a disk image
echo "Creating disk image"
hdiutil create -megabytes $imagesize $imagename -layout NONE

# Associate a device with this but don't mount it
echo "Associating a device with $imagename"
MYDEV=`hdid -nomount $imagename`

# Create a file system
echo "Creating filesystem"
newfs_hfs -v $volumename $MYDEV

# Create a temporary directory in which we will mount the diskimage
echo "Creating mnt/"
mkdir mnt/

# Mount the diskimage
mount_hfs $MYDEV ./mnt/

# Copy stuff to it
echo "Copying $targetname into mnt/"
ditto -rsrcFork $targetname mnt/$targetname

# Unmount
echo "Unmounting"
umount $MYDEV

# Remove the temporary directory
echo "Removing mnt/"
rmdir mnt/

# Eject
echo "Ejecting"
hdiutil eject $MYDEV

# Compress it and make it read only
echo "Compressing"
hdiutil convert -format UDZO $imagename -o $imagename
