#!/bin/bash

version=$1
appdirname=$2

chmod u+x mkdmg

echo "Setting up $appdirname/Contents/MacOS"
mkdir $appdirname/Contents/MacOS
cp /System/Library/Frameworks/JavaVM.framework/Versions/Current/Resources/MacOS/JavaApplicationStub $appdirname/Contents/MacOS/
/Developer/Tools/SetFile -a B $appdirname


# Build standard release
echo "Building standard release: jin-$version-osx.dmg ($appdirname)"
./mkdmg jin-$version-osx.dmg 15 $appdirname

# Build no-extras release
echo "Building no-extras release: jin-$version-osx-no-extras.dmg ($appdirname)"
mv $appdirname/Contents/Resources/Java/resources/pieces/xboard.zip .
rm -f $appdirname/Contents/Resources/Java/resources/pieces/*.zip
mv xboard.zip $appdirname/Contents/Resources/Java/resources/pieces/
./mkdmg jin-$version-osx-no-extras.dmg 5 $appdirname
