#!/bin/sh

# Follow links
filename=`readlink -f $0`
if [ -z "$filename" ]
then
  filename=$0
fi

# Change to Jin's directory - Jin needs to be run from its directory
cd `dirname $filename`

# Run Jin
java $JAVA_OPTS -jar jin.jar $*
